### ISSUE TITLE
Clay cannot be used in GT machines

### ISSUE THREAD

**Issue by msgerbs** [TerraFirmaGreg-Team/Modpack-Vintage#197]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Clay (minecraft:clay_ball) in a compressor should make clay blocks, clay balls in a pulverizer should make clay dust.

### Actual Behavior

Neither of those recipes works, nothing happens.

### Steps to Reproduce

Put clay in the machines.

### Additional Information

This has been happened since at least November according to discord chatters

**Comment by SpeeeDCraft** [comment]
Known issue

**Comment by Exzept1on** [comment]
After a whole year, 1 line of code has been corrected here for that:
https://github.com/TerraFirmaGreg-Team/Core-Vintage/commit/e30111ba67aa87fcaa063f764dcee2a14bfecc91

**Comment by Exzept1on** [comment]
@Xikaro проверь потом пожалуйста.

**Comment by msgerbs** [comment]
Why is that repo private?

**Comment by Exzept1on** [comment]
because :trollface:
