### ISSUE TITLE
Зависает намертво при загрузке мира, повреждение сохранения

### ISSUE THREAD

**Issue by danxnader** [TerraFirmaGreg-Team/Modpack-Vintage#241]
### Версия модпака.

4.5.3

### Среда запуска

Локальная сеть

### С какой стороны краш

Не уверен

### Новые миры

Нет

### Действия по воспроизведению

Непонятно что именно привело к с сбою.
Игра впервые зависла после попытки открыть большой сосуд с маленьким сосудом в руках, однако ранее это не приводило к крашу.
Так же в это время в ямах плавилось несколько сосудов с рудой, до этого момента плавка так же не вызывала проблем.

При загрузке мира игра зависает. Другие миры работают нормально.

### Отчет о сбое

Крашлог первого зависания:
https://gist.github.com/danxnader/e7dd3bba5107cf07d8b968170efd13e1
Полный лог первого зависания (очень большой файл):
https://files.catbox.moe/wjmv16.log
latest при попытке зайти в повреждённый мир:
https://gist.github.com/danxnader/afb9d929908ba2053ef49f917ecf9bb4

### Дополнительная информация

Мир был открыт для локальной сети, второй игрок не совершал никаких действий в момент вылета.
При надобности могу поделиться сохранением.

**Comment by danxnader** [comment]
> стоят у вас какие нибудь ресурс паки?

Лишь идущий со сборкой.
Его отключение не меняет ситуацию.

**Comment by danxnader** [comment]
> Есть возможность прислать мир?
https://files.catbox.moe/93i4xs.rar
> Так же уточни, это началось после обновления?
Мир свежий и создан на 4.5.3. Раньше со сборкой не играл, не обновлял.

**Comment by Furacilin17** [comment]
Точно такая же проблема, пробовал даже запускать сборку с сохранением на других лаунчерах(оф.майн(curseforge) , пиратские лаунчеры(klauncher, tlauncher)), бэкапы помогают, но спустя полчаса-час игры снова вылезает эта проблема

**Comment by danxnader** [comment]
Провёл несколько тестов на другой машине, получилось выловить сейв который стабильно умирает через ~10 минут.
https://files.catbox.moe/5e0151.zip
Крашлоги те же самые.
Из наблюдений: крашит локальную и одиночную игру одинаково, уводит использование оперативки под потолок перед зависанием.
Сборка идентична первой машине.
