### ISSUE TITLE
Генерируется только некоторые виды кучек пыли на поверхности

### ISSUE THREAD

**Issue by Aleevsand** [TerraFirmaGreg-Team/Modpack-Vintage#242]
### Версия модпака.

4.5.3

### Среда запуска

Одиночная игра, сервер Forge

### Новые миры

Да

### Ожидаемое поведение

Корректный спаун кучек пыли для соответствующих жил.

### Фактическое поведение

На поверхности генерируются только Cassiterite Dust, Emerald Dust, Aluminium Dust.

### Действия по воспроизведению

Поставить 4.5.3 версию модпака (ставил через Curse) и создать новый мир, смотреть глазами на землю.

### Дополнительная информация

Возможно генерируются некоторые другие пыли, но отсутствует очень много. По крайней мере медь, графит, мика и т.д. отсутствуют.
Есть подозрение что виноват фикс выпадения Ore Chunk-ов для текущего релиза.

**Comment by Protonm0KEN** [comment]
Согласен. С этой проблемой я также сталкивался в нескольких мирах в надежде что это проблема генерации. Но к сожалению пыльки других видов практически ( я не встречал) не генерируются. Приходилось искать руду копая чанк за чанком
