### ISSUE TITLE
Зависает намертво при загрузке мира/выдает ошибку, повреждение сохранения

### ISSUE THREAD

**Issue by Furacilin17** [TerraFirmaGreg-Team/Modpack-Vintage#243]
### Версия модпака.

4.5.3

### Среда запуска

Одиночная игра + иногда открывал локальных сервер для использования креатива(другие игроки не подключались)

### С какой стороны краш

Клиент

### Новые миры

Не уверен

### Действия по воспроизведению

354 день игры = сбой. Пробовал бэкапы(более 5 раз), играл, но при наступлении 354 игрового дня происходил краш и сохранение больше не запускалось. Даже если пропускать дни с помощью команд и НИЧЕГО не делать, то при наступлении 354 всё равно всё ломается.

### Отчет о сбое

<script src="https://gist.github.com/Furacilin17/bb83488f329ed56dd39ce5eb87d57f54.js"></script> - Краш-репорт
<script src="https://gist.github.com/Furacilin17/d150df4d3c15c5b47fd16b0d703a8bde.js"></script> Latest.log

### Дополнительная информация

_No response_ НЕ РАБОЧЕЕ сохранение: https://cloud.mail.ru/public/xW2N/9LKRim7h2
РАБОЧИЙ МИР: https://cloud.mail.ru/public/mLHF/TBk7LEA5u (Бэкап на 2 игровых дня)

**Comment by Furacilin17** [comment]
Можно как-то это самому исправить, изменив какие-то файлы, к примеру? Ждать обновление ооочень долго

**Comment by Furacilin17** [comment]
Изменение кол-ва дней в месяце(/timetfc set monthlength) вроде как решило проблему, но играть в застывшем марте как-то не очень

**Comment by MrZik1337** [comment]
> Изменение кол-ва дней в месяце(/timetfc set monthlength) вроде как решило проблему, но играть в застывшем марте как-то не очень

Какое количество дней ты установил?

**Comment by Furacilin17** [comment]
Что-то около 2 миллиардов дней в году) 
Краш происходил при наступлении апреля, вот я его и оттянул немножко

**Comment by Xikaro** [comment]
#241
