### ISSUE TITLE
Server crashes on a fresh installation

### ISSUE THREAD

**Issue by JulianVennen** [TerraFirmaGreg-Team/Modpack-Vintage#255]
### Version modpack Used

4.5.5

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

Yes

### Steps to Reproduce

1. Download the server files
2. Install forge
3. Try to start the server

### Crash Report

https://mclo.gs/D1riCDh

**Comment by Xikaro** [comment]
removed from the server !bansoukou-5.0.0.jar, and added the old TerraFirmaCraft-MC1.12.2-1.7.23.181-patched.jar, I wrote to the developer, waiting for a response, the error is only on the server, they can be removed from the server, users log in
[TerraFirmaCraft-MC1.12.2-1.7.23.181-patched.zip](https://github.com/user-attachments/files/17577356/TerraFirmaCraft-MC1.12.2-1.7.23.181-patched.zip)
