### ISSUE TITLE
[🐛]: Выпадают блоки руды вместо кусочков

### ISSUE THREAD

**Issue by AgniaEndie** [TerraFirmaGreg-Team/Modpack-Vintage#260]
### Was this bug reported before?

- [X] No, it was not.

### Version modpack used

4.5.6 - 4.5.7

### Environment

Singleplayer / ForgeServer under Local network

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant.

 https://github.com/TerraFirmaGreg-Team/Modpack-Vintage/issues/233

### Expected Behavior

Абсолютно подобен issue:  https://github.com/TerraFirmaGreg-Team/Modpack-Vintage/issues/233

### Actual Behavior

Абсолютно подобен issue:  https://github.com/TerraFirmaGreg-Team/Modpack-Vintage/issues/233

### Steps to Reproduce

1) Сгенерировать новый мир
2) Найти месторождение руды 
3) Вскопать руду киркой (выплавленной и сконвертированной в вид gregtech (вместо terrafirma) )
4) finish

**Comment by Xikaro** [comment]
Попробуй пожалуйста обновить кор мод
https://www.curseforge.com/minecraft/mc-mods/terrafirmagreg-core/files/5970317

и попробуй снова в сингле

**Comment by AgniaEndie** [comment]
Fixed
